name: Scheduled RSS Refresh
on:
  schedule:
    # This runs at minute 0 of the 5th, 11th, and 17th hour UTC
    # (5am, 11am, 5pm UK time in winter)
    - cron: '0 5,11,17 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
